import fs from "fs/promises";
import path from "path";

const PLAN_FILENAME = "PLAN.md";

function renderStubPlan(repoName: string): string {
  return `# ${repoName} — PLAN

This is the plan for ${repoName}, managed by terrarium.

Terrarium reads this file on each owner wake cycle and files GitHub Issues
for any work items it finds here that don't already have an open issue.

---

## Backlog

<!-- Add work items here. terrarium will file them as GitHub Issues. -->

### Example tasks

- [ ] Set up project structure
- [ ] Add documentation
- [ ] Write initial tests

---

## Guidelines

- Keep items concrete and actionable
- Terrarium will infer complexity labels (low / medium / high) from context
- Items with \`[x]\` (checked) will be skipped
- Remove items that are no longer relevant

---

_This file was generated by \`npx terrarium --install\`._
`;
}

export async function writeStubPlan(
  repoRoot: string,
  repoName: string
): Promise<void> {
  const planPath = path.join(repoRoot, PLAN_FILENAME);

  try {
    await fs.access(planPath);
    // File already exists — do not overwrite
    console.log(`  PLAN.md already exists, skipping`);
    return;
  } catch {
    // File does not exist — write the stub
  }

  await fs.writeFile(planPath, renderStubPlan(repoName), "utf-8");
  console.log(`  Wrote PLAN.md`);
}
